/**
 * MSW **browser** worker (service-worker mode) for the dev server and Playwright E2E.
 *
 * The Node-side equivalent used by Vitest lives in `src/test/server.ts`; this file
 * is the browser counterpart so the running app (not just unit tests) gets the same
 * mocked API. Both share the handlers in {@link handlers}, so the mocked shapes can't
 * drift between unit tests and E2E.
 *
 * Started from `main.tsx` only when mocking is enabled (dev, or `VITE_MSW_ENABLED=true`);
 * never in a production build. Requires `public/mockServiceWorker.js`
 * (generated by `npx msw init public/`).
 */
import { setupWorker } from 'msw/browser'
import { handlers } from './handlers'

/** The browser service worker bound to the default success-scenario handlers. */
export const worker = setupWorker(...handlers)
